name: Abschlussarbeitsthema
description: Neues Thema anlegen
labels: ["topic", "status:open"]
body:

  - type: textarea
    id: summary
    attributes:
      label: Beschreibung
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Aufgaben
      value: |
        - 
        - 

  - type: textarea
    id: prereq
    attributes:
      label: Voraussetzungen
